forge 'http://forge.puppetlabs.com'

# Puppetforge modules
mod 'epel',
    :git => 'https://github.com/stahnma/puppet-module-epel.git'

mod 'hiera',
  :git => 'https://github.com/hunner/puppet-hiera.git'

mod 'ruby',
  :git => 'https://github.com/puppetlabs/puppetlabs-ruby.git'

mod 'r10k',
    :git => 'https://github.com/acidprime/r10k.git',
    :ref => 'v2.8.2'

mod 'puppet'
    :git => 'https://github.com/Brawnd0/abstractit-puppet',
    :ref => 'be_dev'





